/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import form.edit.CustomBtnEdit;
import form.edit.GradientPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author neven
 */
public class ClassForm extends javax.swing.JFrame {

    /**
     * Creates new form ClassForm
     */
    public ClassForm() {
        setResizable(false);
        try {
            
            Image icon = ImageIO.read(new File("C:\\Users\\neven\\Documents\\NetBeansProjects1\\EnrollStudents.Client/iconEnroll.png"));
            setIconImage(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        Color startColor = new Color(200,122,238); 
        Color endColor = new Color(218,248,251);// 200,122,238 new Color(218,248,251);
        
        GradientPanel gradientPanel = new GradientPanel(startColor, endColor);
        setContentPane(gradientPanel);
        initComponents();
        
        CustomBtnEdit btnAdd= new CustomBtnEdit(jButtonAddClass);
        jButtonAddClass.setMinimumSize(new Dimension(200, 35));
        jButtonAddClass.setPreferredSize(new Dimension(200, 35));
        jButtonAddClass.setMaximumSize(new Dimension(200, 35));
        CustomBtnEdit btnBck = new CustomBtnEdit(jButtonBack);
        CustomBtnEdit btnView= new CustomBtnEdit(jButtonView);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClass = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jButtonAddClass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableClass);

        jButtonBack.setText("nazad");

        jButtonView.setText("pregled");

        jButtonAddClass.setText("dodaj odeljenje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAddClass)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonView)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jButtonAddClass)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonView))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JTable getjTableClass() {
        return jTableClass;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTableClass(JTable jTableClass) {
        this.jTableClass = jTableClass;
    }

    public JButton getjButtonView() {
        return jButtonView;
    }

    public void setjButtonView(JButton jButtonView) {
        this.jButtonView = jButtonView;
    }

    public JButton getjButtonAddClass() {
        return jButtonAddClass;
    }

    public void setjButtonAddClass(JButton jButtonAddClass) {
        this.jButtonAddClass = jButtonAddClass;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddClass;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClass;
    // End of variables declaration//GEN-END:variables

    public void backAddActionListener(ActionListener actionListener) {
        jButtonBack.addActionListener(actionListener);
    }

    public void viewBtnAddActionListener(ActionListener actionListener) {
        jButtonView.addActionListener(actionListener);
    }

    public void addClassBtnAddActionListener(ActionListener actionListener) {
        jButtonAddClass.addActionListener(actionListener);
    }

    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public void setjButtonBack(JButton jButtonBack) {
        this.jButtonBack = jButtonBack;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }
    
    
}
