/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import coordinator.Coordinator;
import domain.City;
import form.edit.CustomBtnEdit;
import form.edit.GradientPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.text.StyleConstants;

/**
 *
 * @author neven
 */
public class MainForm extends javax.swing.JFrame {

    
    private ResourceBundle bundle;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        setLayout(null);
        Color startColor = new Color(218,248,251); 
        Color endColor = new Color(200,122,238);// 200,122,238
        
        GradientPanel gradientPanel = new GradientPanel(startColor, endColor);
        setContentPane(gradientPanel);
        
        Coordinator.getInstance().setCurrentLocale(new Locale("sr", "RS"));
        bundle = ResourceBundle.getBundle("resources.messages", Coordinator.getInstance().getCurrentLocale());
        
        initComponents();
        
        CustomBtnEdit btnDel = new CustomBtnEdit(jButtonDelete);
         btnDel.setAlignment(1200, 800);
         CustomBtnEdit btnNext = new CustomBtnEdit(jButtonNext);
         CustomBtnEdit btnView = new CustomBtnEdit(jButtonView);
        localizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelLogged = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSchoolName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCity = new javax.swing.JComboBox<>();
        jButtonNext = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jButtonEnglish = new javax.swing.JButton();
        jButtonSrbLat = new javax.swing.JButton();
        jLabelLoggedIn = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSchool = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAddSch = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAddStud = new javax.swing.JMenuItem();
        jMenuItemViewAllStud = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAddCls = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelLogged.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Zdravo,");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Naziv skole: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Grad:");

        jButtonNext.setText("dalje");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonDelete.setText("obriši");

        jButtonView.setText("pregled");

        jButtonEnglish.setText("ENG");
        jButtonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnglishActionPerformed(evt);
            }
        });

        jButtonSrbLat.setText("LAT");
        jButtonSrbLat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSrbLatActionPerformed(evt);
            }
        });

        jLabelLoggedIn.setText("nesto nesto");

        jTableSchool.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTableSchool);

        jMenu1.setText("Skola");

        jMenuItemAddSch.setText("dodaj");
        jMenuItemAddSch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddSchActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAddSch);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ucenik");

        jMenuItemAddStud.setText("dodaj");
        jMenu2.add(jMenuItemAddStud);

        jMenuItemViewAllStud.setText("pregled");
        jMenu2.add(jMenuItemViewAllStud);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Odeljenje");

        jMenuItemAddCls.setText("dodaj");
        jMenu3.add(jMenuItemAddCls);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogged)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel2)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSchoolName)
                            .addComponent(jComboBoxCity, 0, 150, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLoggedIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 576, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonDelete)
                                    .addComponent(jButtonView))
                                .addGap(70, 70, 70))
                            .addComponent(jButtonNext, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSrbLat)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEnglish)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogged)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSrbLat)
                            .addComponent(jButtonEnglish))
                        .addGap(212, 212, 212)
                        .addComponent(jButtonView)
                        .addGap(89, 89, 89)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLoggedIn)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAddSchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddSchActionPerformed
        // ODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAddSchActionPerformed

    private void jButtonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnglishActionPerformed
        Coordinator.getInstance().setCurrentLocale(new Locale("en", "US"));
        bundle = ResourceBundle.getBundle("resources.messages", Coordinator.getInstance().getCurrentLocale());
        localizeComponents();
        updateTableHeaders();
    }//GEN-LAST:event_jButtonEnglishActionPerformed

    private void jButtonSrbLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSrbLatActionPerformed
        Coordinator.getInstance().setCurrentLocale(new Locale("sr", "RS"));
        bundle = ResourceBundle.getBundle("resources.messages", Coordinator.getInstance().getCurrentLocale());
        localizeComponents();
        updateTableHeaders();
    }//GEN-LAST:event_jButtonSrbLatActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    public JLabel getjLabelLoggedIn() {
        return jLabelLoggedIn;
    }

    public void setjLabelLoggedIn(JLabel jLabelLoggedIn) {
        this.jLabelLoggedIn = jLabelLoggedIn;
    }

    public JTable getjTableSchool() {
        return jTableSchool;
    }

    public void setjTableSchool(JTable jTableSchool) {
        this.jTableSchool = jTableSchool;
    }

    public JComboBox<City> getjComboBoxCity() {
        return jComboBoxCity;
    }

    public void setjComboBoxCity(JComboBox<City> jComboBoxCity) {
        this.jComboBoxCity = jComboBoxCity;
    }

    public JTextField getjTextFieldSchoolName() {
        return jTextFieldSchoolName;
    }

    public void setjTextFieldSchoolName(JTextField jTextFieldSchoolName) {
        this.jTextFieldSchoolName = jTextFieldSchoolName;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEnglish;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSrbLat;
    private javax.swing.JButton jButtonView;
    private javax.swing.JComboBox<City> jComboBoxCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogged;
    private javax.swing.JLabel jLabelLoggedIn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAddCls;
    private javax.swing.JMenuItem jMenuItemAddSch;
    private javax.swing.JMenuItem jMenuItemAddStud;
    private javax.swing.JMenuItem jMenuItemViewAllStud;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSchool;
    private javax.swing.JTextField jTextFieldSchoolName;
    // End of variables declaration//GEN-END:variables

    public void comboBoxAddActionListener(ActionListener actionListener) {
        jComboBoxCity.addActionListener(actionListener);
    }

    public void SearchSchoolAddActionListener(ActionListener actionListener) {
        jTextFieldSchoolName.addActionListener(actionListener);
    }

    public JButton getjButtonDelete() {
        return jButtonDelete;
    }

    public void setjButtonDelete(JButton jButtonDelete) {
        this.jButtonDelete = jButtonDelete;
    }

    public void deleteSchoolAddActionListener(ActionListener actionListener) {
        jButtonDelete.addActionListener(actionListener);
    }

    public JButton getjButtonNext() {
        return jButtonNext;
    }

    public void setjButtonNext(JButton jButtonNext) {
        this.jButtonNext = jButtonNext;
    }

    public void nextAddCtionListener(ActionListener actionListener) {
        jButtonNext.addActionListener(actionListener);
    }

    public JButton getjButtonView() {
        return jButtonView;
    }

    public void setjButtonView(JButton jButtonView) {
        this.jButtonView = jButtonView;
    }

    public void viewAddCtionListener(ActionListener actionListener) {
        jButtonView.addActionListener(actionListener);
    }

    public JMenuItem getjMenuItemAddSch() {
        return jMenuItemAddSch;
    }

    public void setjMenuItemAddSch(JMenuItem jMenuItemAddSch) {
        this.jMenuItemAddSch = jMenuItemAddSch;
    }

    

    public void addSchAddActionListener(ActionListener actionListener) {
        jMenuItemAddSch.addActionListener(actionListener);
    }

    public JMenuItem getjMenuItemAddCls() {
        return jMenuItemAddCls;
    }

    public void setjMenuItemAddCls(JMenuItem jMenuItemAddCls) {
        this.jMenuItemAddCls = jMenuItemAddCls;
    }

  

    public void addClssAddActionListener(ActionListener actionListener) {
        jMenuItemAddCls.addActionListener(actionListener);
    }

    public JMenuItem getjMenuItemAddStud() {
        return jMenuItemAddStud;
    }

    public void setjMenuItemAddStud(JMenuItem jMenuItemAddStud) {
        this.jMenuItemAddStud = jMenuItemAddStud;
    }

    public void addStudAddActionListener(ActionListener actionListener) {
        jMenuItemAddStud.addActionListener(actionListener);
    }

    public JMenuItem getjMenuItemViewAllStud() {
        return jMenuItemViewAllStud;
    }

    public void setjMenuItemViewAllStud(JMenuItem jMenuItemViewAllStud) {
        this.jMenuItemViewAllStud = jMenuItemViewAllStud;
    }

    public void viewAllStudAddActionListener(ActionListener actionListener) {
        jMenuItemViewAllStud.addActionListener(actionListener);
    }

   

    private void localizeComponents() {
        try {
            jLabel1.setText(bundle.getString("greeting"));
            jMenu1.setText(capitalizeFirstLetter(bundle.getString("school")));
            jMenu1.revalidate();
            jMenu1.repaint();
        
        jMenu2.setText(capitalizeFirstLetter(bundle.getString("student")));
        jMenu3.setText(capitalizeFirstLetter(bundle.getString("class")));
        jMenuItemAddSch.setText(capitalizeFirstLetter(bundle.getString("add")));
        jMenuItemAddStud.setText(capitalizeFirstLetter(bundle.getString("add")));
        jMenuItemViewAllStud.setText(capitalizeFirstLetter(bundle.getString("view")));
        jMenuItemAddCls.setText(capitalizeFirstLetter(bundle.getString("add")));
        jLabel2.setText(capitalizeFirstLetter(bundle.getString("name_of_school")));
        jLabel3.setText(capitalizeFirstLetter(bundle.getString("city")));
        
        jButtonDelete.setText(bundle.getString("btn.delete"));
        jButtonView.setText(bundle.getString("view"));
        jButtonNext.setText(bundle.getString("btn.next"));
       
            
        } catch (MissingResourceException e) {
             System.err.println("Key '' not found in resource bundle.");
        }
        
        
    }

    private void updateTableHeaders() {
        String[] newColumnNames = {
            bundle.getString("schoolID"),
            bundle.getString("name_of_school"),
            bundle.getString("adress"),
            bundle.getString("phone"),
            bundle.getString("city")
        };

        ((TableModelSchool) jTableSchool.getModel()).updateColumnNames(newColumnNames);
        jTableSchool.revalidate();
        jTableSchool.repaint();
       
    }

    public JButton getjButtonEnglish() {
        return jButtonEnglish;
    }

    public void setjButtonEnglish(JButton jButtonEnglish) {
        this.jButtonEnglish = jButtonEnglish;
    }

    public JButton getjButtonSrbLat() {
        return jButtonSrbLat;
    }

    public void setjButtonSrbLat(JButton jButtonSrbLat) {
        this.jButtonSrbLat = jButtonSrbLat;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    
    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    private String capitalizeFirstLetter(String string) {
        return string.substring(0, 1).toUpperCase() + string.substring(1);
    }

   

   

   
    
}
