/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.City;
import form.edit.CustomBtnEdit;
import form.edit.GradientPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author neven
 */
public class ViewSchoolForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewSchoolForm
     */
    public ViewSchoolForm() {
        setResizable(false);
        try {
            
            Image icon = ImageIO.read(new File("C:\\Users\\neven\\Documents\\NetBeansProjects1\\EnrollStudents.Client/iconEnroll.png"));
            setIconImage(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        Color startColor = new Color(200,122,238); 
        Color endColor = new Color(218,248,251);// 200,122,238 new Color(218,248,251);
        
        GradientPanel gradientPanel = new GradientPanel(startColor, endColor);
        setContentPane(gradientPanel);

        initComponents();
        
        CustomBtnEdit btnAdd = new CustomBtnEdit(jButtonAdd);
        CustomBtnEdit btnBck = new CustomBtnEdit(jButtonCncel);
        CustomBtnEdit btnUpdate = new CustomBtnEdit(jButtonUpdate);
        
        jLabel1.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel1.setForeground(Color.WHITE);
        jLabel2.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel2.setForeground(Color.WHITE);
        jLabel3.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel3.setForeground(Color.WHITE);
        jLabel4.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel4.setForeground(Color.WHITE);
        jLabelCity1.setFont(new Font("Arial", Font.BOLD, 16));
        jLabelCity1.setForeground(Color.WHITE);
        
        jTextFieldAdress.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldName.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldPhone.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldSchoolID.setFont(new Font("Arial", Font.BOLD, 16));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldSchoolID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAdress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabelCity1 = new javax.swing.JLabel();
        jButtonCncel = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jComboBoxCity = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("schoolID: ");

        jTextFieldSchoolID.setText("jTextField1");

        jLabel2.setText("Naziv: ");

        jTextFieldName.setText("jTextField1");

        jLabel3.setText("Adresa: ");

        jTextFieldAdress.setText("jTextField1");

        jLabel4.setText("Telefon: ");

        jTextFieldPhone.setText("jTextField1");

        jLabelCity1.setText("Grad:");

        jButtonCncel.setText("otkaži");

        jButtonUpdate.setText("ažuriraj");

        jButtonAdd.setText("dodaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabelCity1)
                            .addComponent(jLabel1))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldSchoolID)
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldAdress)
                            .addComponent(jTextFieldPhone))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCncel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpdate)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSchoolID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCity1)
                    .addComponent(jComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCncel)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonUpdate))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonCncel() {
        return jButtonCncel;
    }

    public void setjButtonCncel(JButton jButtonCncel) {
        this.jButtonCncel = jButtonCncel;
    }

    public JButton getjButtonUpdate() {
        return jButtonUpdate;
    }

    public void setjButtonUpdate(JButton jButtonUpdate) {
        this.jButtonUpdate = jButtonUpdate;
    }


    public JTextField getjTextFieldAdress() {
        return jTextFieldAdress;
    }

    public void setjTextFieldAdress(JTextField jTextFieldAdress) {
        this.jTextFieldAdress = jTextFieldAdress;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public void setjTextFieldName(JTextField jTextFieldName) {
        this.jTextFieldName = jTextFieldName;
    }

    public JTextField getjTextFieldPhone() {
        return jTextFieldPhone;
    }

    public void setjTextFieldPhone(JTextField jTextFieldPhone) {
        this.jTextFieldPhone = jTextFieldPhone;
    }

    public JTextField getjTextFieldSchoolID() {
        return jTextFieldSchoolID;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTextFieldSchoolID(JTextField jTextFieldSchoolID) {
        this.jTextFieldSchoolID = jTextFieldSchoolID;
    }

    public JButton getjButtonAdd() {
        return jButtonAdd;
    }

    public void setjButtonAdd(JButton jButtonAdd) {
        this.jButtonAdd = jButtonAdd;
    }

    public JComboBox<City> getjComboBoxCity() {
        return jComboBoxCity;
    }

    public void setjComboBoxCity(JComboBox<City> jComboBoxCity) {
        this.jComboBoxCity = jComboBoxCity;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCncel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<City> jComboBoxCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCity1;
    private javax.swing.JTextField jTextFieldAdress;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldSchoolID;
    // End of variables declaration//GEN-END:variables

    public void backAddActionListener(ActionListener actionListener) {
        jButtonCncel.addActionListener(actionListener);
    }

    public void addBtnAddActionListener(ActionListener actionListener) {
        jButtonAdd.addActionListener(actionListener);
    }

    public void updateBtnAddActionListener(ActionListener actionListener) {
        jButtonUpdate.addActionListener(actionListener);
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabelCity1() {
        return jLabelCity1;
    }

    public void setjLabelCity1(JLabel jLabelCity1) {
        this.jLabelCity1 = jLabelCity1;
    }
    
    
}
