/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.City;
import form.edit.CustomBtnEdit;
import form.edit.GradientPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author neven
 */
public class ViewStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudentForm
     */
    public ViewStudentForm() {
        setResizable(false);
        setSize(300, 800);
        try {
            
            Image icon = ImageIO.read(new File("C:\\Users\\neven\\Documents\\NetBeansProjects1\\EnrollStudents.Client/iconEnroll.png"));
            setIconImage(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        Color startColor = new Color(200,122,238); 
        Color endColor = new Color(218,248,251);// 200,122,238 new Color(218,248,251);
        
        GradientPanel gradientPanel = new GradientPanel(startColor, endColor);
        setContentPane(gradientPanel);
        
        
        initComponents();
        
        CustomBtnEdit btnUpdate = new CustomBtnEdit(jButtonUpdate);
        CustomBtnEdit btnAdd = new CustomBtnEdit(jButtonAdd);
        CustomBtnEdit btnBack = new CustomBtnEdit(jButtonBack);
        
        jLabel1.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel1.setForeground(Color.WHITE);
        jLabel2.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel2.setForeground(Color.WHITE);
        jLabel3.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel3.setForeground(Color.WHITE);
        jLabel4.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel4.setForeground(Color.WHITE);
        jLabel5.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel5.setForeground(Color.WHITE);
        jLabel6.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel6.setForeground(Color.WHITE);
        jLabel7.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel7.setForeground(Color.WHITE);
        
        jTextFieldJMBG.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldBirhday.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldName.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldParent.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldSurname.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldStudentID.setFont(new Font("Arial", Font.BOLD, 16));
        
        jComboBoxCity.setFont(new Font("Arial", Font.BOLD, 16));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldStudentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldJMBG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldBirhday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldParent = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jComboBoxCity = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("studentID: ");

        jLabel2.setText("JMBG: ");

        jLabel3.setText("Ime: ");

        jLabel4.setText("Prezime: ");

        jLabel5.setText("Rodjendan: ");

        jLabel6.setText("Roditelj: ");

        jLabel7.setText("Grad: ");

        jButtonBack.setText("nazad");

        jButtonUpdate.setText("ažuriraj");

        jButtonAdd.setText("dodaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdate)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldParent, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldJMBG, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBirhday, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCity, 0, 200, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldBirhday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonAdd))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public void setjButtonBack(JButton jButtonBack) {
        this.jButtonBack = jButtonBack;
    }

    public JButton getjButtonUpdate() {
        return jButtonUpdate;
    }

    public void setjButtonUpdate(JButton jButtonUpdate) {
        this.jButtonUpdate = jButtonUpdate;
    }

    public JTextField getjTextFieldBirhday() {
        return jTextFieldBirhday;
    }

    public void setjTextFieldBirhday(JTextField jTextFieldBirhday) {
        this.jTextFieldBirhday = jTextFieldBirhday;
    }

    public JComboBox<City> getjComboBoxCity() {
        return jComboBoxCity;
    }

    public void setjComboBoxCity(JComboBox<City> jComboBoxCity) {
        this.jComboBoxCity = jComboBoxCity;
    }

    

    public JTextField getjTextFieldJMBG() {
        return jTextFieldJMBG;
    }

    public void setjTextFieldJMBG(JTextField jTextFieldJMBG) {
        this.jTextFieldJMBG = jTextFieldJMBG;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public void setjTextFieldName(JTextField jTextFieldName) {
        this.jTextFieldName = jTextFieldName;
    }

    public JTextField getjTextFieldParent() {
        return jTextFieldParent;
    }

    public void setjTextFieldParent(JTextField jTextFieldParent) {
        this.jTextFieldParent = jTextFieldParent;
    }

    public JTextField getjTextFieldStudentID() {
        return jTextFieldStudentID;
    }

    public void setjTextFieldStudentID(JTextField jTextFieldStudentID) {
        this.jTextFieldStudentID = jTextFieldStudentID;
    }

    public JTextField getjTextFieldSurname() {
        return jTextFieldSurname;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTextFieldSurname(JTextField jTextFieldSurname) {
        this.jTextFieldSurname = jTextFieldSurname;
    }

    public JButton getjButtonAdd() {
        return jButtonAdd;
    }

    public void setjButtonAdd(JButton jButtonAdd) {
        this.jButtonAdd = jButtonAdd;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<City> jComboBoxCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldBirhday;
    private javax.swing.JTextField jTextFieldJMBG;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldParent;
    private javax.swing.JTextField jTextFieldStudentID;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables

    public void backBtnAddActionListener(ActionListener actionListener) {
        jButtonBack.addActionListener(actionListener);
    }

    public void updateAddActionListener(ActionListener actionListener) {
        jButtonUpdate.addActionListener(actionListener);
    }

    public void addStudAddActionListener(ActionListener actionListener) {
        jButtonAdd.addActionListener(actionListener);
    }
}
