/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import form.edit.CustomBtnEdit;
import form.edit.GradientPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author neven
 */
public class ViewClassForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewClassForm
     */
    public ViewClassForm() {
        setResizable(false);
        try {
            
            Image icon = ImageIO.read(new File("C:\\Users\\neven\\Documents\\NetBeansProjects1\\EnrollStudents.Client/iconEnroll.png"));
            setIconImage(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        Color startColor = new Color(200,122,238); 
        Color endColor = new Color(218,248,251);// 200,122,238 new Color(218,248,251);
        
        GradientPanel gradientPanel = new GradientPanel(startColor, endColor);
        setContentPane(gradientPanel);
        initComponents();
        
        CustomBtnEdit btnView= new CustomBtnEdit(jButtonViewStudent);
        CustomBtnEdit btnEnroll= new CustomBtnEdit(jButtonEnrollNewStud);
        CustomBtnEdit btnBack = new CustomBtnEdit(jButtonBack);
        CustomBtnEdit btnSaveChange = new CustomBtnEdit(jButtonSaveChanges);
        
        jButtonEnrollNewStud.setMinimumSize(new Dimension(150, 35));
        jButtonEnrollNewStud.setPreferredSize(new Dimension(150, 35));
        jButtonEnrollNewStud.setMaximumSize(new Dimension(150, 35));
        
        jButtonSaveChanges.setMinimumSize(new Dimension(200, 35));
        jButtonSaveChanges.setPreferredSize(new Dimension(200, 35));
        jButtonSaveChanges.setMaximumSize(new Dimension(200, 35));
        
        jLabel1.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel1.setForeground(Color.WHITE);
        jLabel2.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel2.setForeground(Color.WHITE);
        jLabel3.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel3.setForeground(Color.WHITE);
        jLabel4.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel4.setForeground(Color.WHITE);
        jLabel5.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel5.setForeground(Color.WHITE);
        jLabelName.setFont(new Font("Arial", Font.BOLD, 16));
        jLabelName.setForeground(Color.WHITE);
        
        jTextFieldClassID.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldGrade.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldName.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldNumOfStud.setFont(new Font("Arial", Font.BOLD, 16));
        jTextFieldSchool.setFont(new Font("Arial", Font.BOLD, 16));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldClassID = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNumOfStud = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSchool = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonEnrollNewStud = new javax.swing.JButton();
        jButtonViewStudent = new javax.swing.JButton();
        jButtonSaveChanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTableStudent);

        jLabel1.setText("classID: ");

        jLabelName.setText("naziv: ");

        jLabel2.setText("broj ucenika: ");

        jLabel3.setText("razred: ");

        jLabel4.setText("skola: ");

        jLabel5.setText("Lista ucenika: ");

        jButtonBack.setText("nazad");

        jButtonEnrollNewStud.setText("dodaj učenike");

        jButtonViewStudent.setText("pregled");

        jButtonSaveChanges.setText("sačuvaj izmene");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumOfStud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonViewStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSaveChanges)
                            .addComponent(jButtonEnrollNewStud))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNumOfStud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonViewStudent)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnrollNewStud)
                    .addComponent(jButtonBack))
                .addGap(18, 18, 18)
                .addComponent(jButtonSaveChanges)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public void setjButtonBack(JButton jButtonBack) {
        this.jButtonBack = jButtonBack;
    }

    public JButton getjButtonEnrollNewStud() {
        return jButtonEnrollNewStud;
    }

    public void setjButtonEnrollNewStud(JButton jButtonEnrollNewStud) {
        this.jButtonEnrollNewStud = jButtonEnrollNewStud;
    }

    public JTextField getjTextFieldClassID() {
        return jTextFieldClassID;
    }

    public void setjTextFieldClassID(JTextField jTextFieldClassID) {
        this.jTextFieldClassID = jTextFieldClassID;
    }

    public JTextField getjTextFieldGrade() {
        return jTextFieldGrade;
    }

    public void setjTextFieldGrade(JTextField jTextFieldGrade) {
        this.jTextFieldGrade = jTextFieldGrade;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public void setjTextFieldName(JTextField jTextFieldName) {
        this.jTextFieldName = jTextFieldName;
    }

    public JTextField getjTextFieldNumOfStud() {
        return jTextFieldNumOfStud;
    }

    public void setjTextFieldNumOfStud(JTextField jTextFieldNumOfStud) {
        this.jTextFieldNumOfStud = jTextFieldNumOfStud;
    }

    public JTextField getjTextFieldSchool() {
        return jTextFieldSchool;
    }

    public JTable getjTableStudent() {
        return jTableStudent;
    }

    public void setjTableStudent(JTable jTableStudent) {
        this.jTableStudent = jTableStudent;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTextFieldSchool(JTextField jTextFieldSchool) {
        this.jTextFieldSchool = jTextFieldSchool;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonEnrollNewStud;
    private javax.swing.JButton jButtonSaveChanges;
    private javax.swing.JButton jButtonViewStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTextField jTextFieldClassID;
    private javax.swing.JTextField jTextFieldGrade;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumOfStud;
    private javax.swing.JTextField jTextFieldSchool;
    // End of variables declaration//GEN-END:variables

    public void backBtnAddActionListener(ActionListener actionListener) {
        jButtonBack.addActionListener(actionListener);
    }

    public void enrollStudentBtnAddActionListener(ActionListener actionListener) {
        jButtonEnrollNewStud.addActionListener(actionListener);
    }

    public void viewStudBtnAddActionListener(ActionListener actionListener) {
        jButtonViewStudent.addActionListener(actionListener);
    }

    public JButton getjButtonViewStudent() {
        return jButtonViewStudent;
    }

    public void setjButtonViewStudent(JButton jButtonViewStudent) {
        this.jButtonViewStudent = jButtonViewStudent;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabelName() {
        return jLabelName;
    }

    public void setjLabelName(JLabel jLabelName) {
        this.jLabelName = jLabelName;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JButton getjButtonSaveChanges() {
        return jButtonSaveChanges;
    }

    public void setjButtonSaveChanges(JButton jButtonSaveChanges) {
        this.jButtonSaveChanges = jButtonSaveChanges;
    }

    public void saveChangeAddActionListener(ActionListener actionListener) {
        jButtonSaveChanges.addActionListener(actionListener);
    }
    
    
}
