/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import controller.Controller;
import domain.School;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author neven
 */
public class ViewTableSchool extends javax.swing.JFrame {
    List<School> listSch;
    int[] classCount;
    
    /**
     * Creates new form ViewTableSchool
     */
    public ViewTableSchool() {
        try {
            this.listSch = Controller.getInstance().getAllSchools();
        } catch (Exception ex) {
            Logger.getLogger(ViewTableSchool.class.getName()).log(Level.SEVERE, null, ex);
        }
        classCount = getClassCount();
        initComponents();
        setLocationRelativeTo(this);
        
        TableModelSchool tms = new TableModelSchool(listSch, classCount);
        jTableSchool.setModel(tms);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSchool = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableSchool.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSchool);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSchool;
    // End of variables declaration//GEN-END:variables

    private int[] getClassCount() {
        int [] count = new int[listSch.size()];
        int i = 0;
        
        for (School school : listSch) {
            try {
                count[i] =  Controller.getInstance().GetNumOfClasses(school.getSchoolID());
            } catch (Exception ex) {
                Logger.getLogger(ViewTableSchool.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
        }
        for (int j : count) {
            System.out.print(j+ ", ");
        }
        return count;
    }
}
